modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[modproperties."${mod_id}"]
    catalogueItemIcon="${mod_id}:diamond_multitool"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
logoBlur=false
updateJSONURL = "https://raw.githubusercontent.com/BlatFan/mod_updates/main/blatblock.json"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="curios"
mandatory=false
versionRange="[${curios_version}, )"
ordering="BEFORE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="blatapi"
mandatory=true
versionRange="[${blatapi_version}, )"
ordering="BEFORE"
side="BOTH"